# Generated by Django 4.1.7 on 2023-04-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_choice_text_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['choice_text'], name='polls_choic_choice__456eec_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_text'], name='polls_quest_questio_13fa43_idx'),
        ),
    ]
